CC = gcc
CFLAGS = -g

.PHONY: clear
.SUFFIXES: .h .o .c .a .so 

.c.o:
	$(CC) $(CFLAGS) -c $<

.o:
	$(CC) $(CFLAGS) -o $@ $^ -Wl,-rpath,.

Code2.o: Code2.c
	$(CC) $(CFLAGS) -c $^

libpole.a: pole.o
	ar rs $@ $<

libobjetosc.so: objetosc.o
	$(CC) $(CFLAGS) -shared -o $@ $<

pole.o: pole.c
	$(CC) $(CFLAGS) -c $<

objetosc.o: objetosc.c
	$(CC) $(CFLAGS) -c -fPIC $<

clear:
	rm -f *.o *.a *.so Code2
