CC = gcc
CFLAGS = -g

.PHONY: clear
.SUFFIXES: .h .o .c .a .so 

%: %.o
	$(CC) $(CFLAGS) -o $@ $^ -Wl,-rpath,.

%.o: %.c
	$(CC) $(CFLAGS) -c $^

lib%.a: %.o
	ar rs $@ $<

lib%.so: %.o
	$(CC) $(CFLAGS) -shared -o $@ $<

%S.o: %.c
	$(CC) $(CFLAGS) -c $<

%D.o: %.c
	$(CC) $(CFLAGS) -c -fPIC $<

Code2: Code2.o libpole.a libobjetosc.so
Code2.o: Code2.c
libpole.a: pole.o
libobjetosc.so: objetosc.o
poleS.o: pole.c
objetoscD.o: objetosc.c

clear:
	rm -f *.o *.a *.so Code2
